name: Bug Report
description: File a bug / issue

title: "bug: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        **Before** reporting an issue, make sure to read the [Troubleshooting section](https://github.com/Hdoc1509/gh-actions.nvim#troubleshooting)
        and search [existing issues](https://github.com/Hdoc1509/gh-actions.nvim/issues).

  - type: checkboxes
    attributes:
      label: Did you check docs and existing issues?
      description: Make sure you checked all of the below before submitting an issue
      options:
        - label: I have read the Troubleshooting section
          required: true
        - label: I have updated the plugin to the latest version before submitting this issue
          required: true
        - label: I have searched the existing issues of gh-actions.nvim
          required: true
        - label: I have searched the existing issues of plugins related to this issue
          required: true

  - type: input
    attributes:
      label: Neovim version (nvim -v)
      placeholder: 0.10.0
    validations:
      required: true

  - type: input
    attributes:
      label: Operating system
      placeholder: Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A description of what the bug is. You can use markdown, screenshots and include error messages from Neovim.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Healthcheck output
      description: Output of `:checkhealth vim.treesitter` and `:checkhealth nvim-treesitter`
    validations:
      required: true

  - type: textarea
    attributes:
      label: Repro
      description: Minimal `init.lua` to reproduce this issue. Save as `repro.lua` and run with `nvim --clean -u repro.lua`. Check examples in [`minit` folder](https://github.com/Hdoc1509/gh-actions.nvim/tree/master/minit).
      value: |
        -- NOTE: pick a template from `minit` folder and use it here
      render: lua
    validations:
      required: true
